### ISSUE TITLE
AttributeError: 'list' object has no attribute 'model_dump'

### ISSUE THREAD

**Issue by eresque** [open-webui/pipelines#24]
## **Error**
In `main.py` the Pydantic method `model_dump()` is used in 529 string as of now, in `generate_openai_chat_completion` function:
```
user_message = get_last_user_message(form_data.messages.model_dump())
```
This causes an error, because `form_data.messages` is a list containing `OpenAIChatMessage` objects and not an object itself.

---
## **Fix**
Removing  `model_dump()` from `generate_openai_chat_completion` function in `main.py`:
```
user_message = get_last_user_message(form_data.messages)
```
And adding `model_dump()` to a function `get_last_user_message` in file `utils/main.py`:
```
def get_last_user_message(messages: List[dict]) -> str:
    for message in reversed(messages):
        message = message.model_dump()
```
fixes the error.

**Comment by tjbck** [comment]
Fixed a while back, Try pulling the latest!

**Comment by arsaboo** [comment]
@tjbck I am still seeing this error with 0.3.32:
```bash
ERROR [open_webui.apps.retrieval.utils] Error when querying the collection: 'NoneType' object has no attribute 'model_dump'
Traceback (most recent call last):
  File "/app/backend/open_webui/apps/retrieval/utils.py", line 196, in query_collection
    results.append(result.model_dump())
                   ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'model_dump'```

This is sometimes followed by another error:

```bash
INFO:     X.Y.Z.X:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=P9ieJ95&sid=KmUCneyS6NrGGLFvAAAL HTTP/1.1" 200 OK
post request handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/engineio/async_server.py", line 306, in handle_request
    await socket.handle_post_request(environ)
  File "/usr/local/lib/python3.11/site-packages/engineio/async_socket.py", line 109, in handle_post_request
    p = payload.Payload(encoded_payload=body)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/engineio/payload.py", line 13, in __init__
    self.decode(encoded_payload)
  File "/usr/local/lib/python3.11/site-packages/engineio/payload.py", line 44, in decode
    raise ValueError('Too many packets in payload')
ValueError: Too many packets in payload
ERROR [engineio.server] post request handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/engineio/async_server.py", line 306, in handle_request
    await socket.handle_post_request(environ)
  File "/usr/local/lib/python3.11/site-packages/engineio/async_socket.py", line 109, in handle_post_request
    p = payload.Payload(encoded_payload=body)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/engineio/payload.py", line 13, in __init__
    self.decode(encoded_payload)
  File "/usr/local/lib/python3.11/site-packages/engineio/payload.py", line 44, in decode
    raise ValueError('Too many packets in payload')
ValueError: Too many packets in payload```
